version: '3.9'
services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    environment:
      DJANGO_SETTINGS_MODULE: core.settings.production
    depends_on: [postgres, redis]
    expose: ['8000']

  frontend:
    build:
      context: ./frontend
    expose: ['80']

  nginx:
    image: nginx:1.27-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - '80:80'
    depends_on: [frontend, backend]

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: nexos_db
      POSTGRES_USER: nexos_user
      POSTGRES_PASSWORD: nexos_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine

volumes:
  postgres_data:
